### PR TITLE
Add upsert option to upload/update

### PR DESCRIPTION
**Pull request by clefelhocz2**
## What kind of change does this PR introduce?

This is to address issue https://github.com/supabase-community/supabase-py/issues/693.  Documentation said we could use the upsert option, but user would have to specify x-upsert.  

I also updated pre-commit hooks as the version of autoflake is old enough to still require distutils which no longer exists in python 3.12.  

## What is the current behavior?
Old behavior code:
```
with open(filepath, 'rb') as f:
  supabase.storage.from_("bucket_name").update(file=f, path=path_on_supastorage, file_options={"cache-control": "3600", "upsert": "true"})
```
would not pass along the upsert option to server side.

New behavior:
```
with open(filepath, 'rb') as f:
  supabase.storage.from_("bucket_name").update(file=f, path=path_on_supastorage, file_options={"cache-control": "3600", "upsert": "true"})
```
Is passed along as x-upsert header option.

Please link any relevant issues here.
https://github.com/supabase-community/supabase-py/issues/693

## What is the new behavior?
See above

Feel free to include screenshots if it includes visual changes.

## Additional context
This addresses the client side operation.  

Add any other context or screenshots.

### CODE REVIEW

**Review by silentworks — CHANGES_REQUESTED** [review]
The `.pre-commit-config.yaml` file has been modified but the formatting of this shouldn't have changed. Also did you use the `make build_sync` command to create the changes in the `_sync/` directory? if not this is how you should do it and not make manual edits to the `_sync/` directory.

**Comment by clefelhocz2** [comment]
> The `.pre-commit-config.yaml` file has been modified but the formatting of this shouldn't have changed. Also did you use the `make build_sync` command to create the changes in the `_sync/` directory? if not this is how you should do it and not make manual edits to the `_sync/` directory.

Okay, I updated my editor to not autosave on yaml (that was the problem there) and ran make build_sync to copy over the changes.   I uploaded, but didn't squash.  Let me know if we need to squash as well for this type of work.  

Let me know any additional feedback and if there is another issue to go after.

**Comment by silentworks** [comment]
@clefelhocz2 thanks for this, I'm going to ask for one more update, can you change the `upsert` to match that of the JS library so it only does `upsert` on `POST` requests. I've opened an issue on the storage-js repo to ask about this behaviour but would prefer if we followed it for now so we can merge this in and then change if I get a reply that the behaviour in the JavaScript library is incorrect. https://github.com/supabase/storage-js/issues/194

**Comment by clefelhocz2** [comment]
Thanks.  Will start on updating the PR today and hopefully have it over soon.

**Comment by clefelhocz2** [comment]
@silentworks I was able to update per your guidance.  It looks different than the javascript code, but that's because the javascript code actually works differently.  The options are copied into headers based on different filetypes, duplex, etc.   It isn't a great implementation as adding a new default to DEFAULT_FILE_OPTIONS isn't going to add it to the headers based on my reading.  

Let me know any feedback and/or new issue I could tackle.  I was looking at https://github.com/supabase-community/auth-py/issues/320, but it looks involved.

**Review by silentworks — APPROVED** [review]

**Comment by silentworks** [comment]
@clefelhocz2 thanks for this PR. The change will be out in the next release of the library. In regards to the other issue, lets move the conversation to the issue itself. It is involved but I can guide you through it a bit.

**Pull request merged**
